#!/usr/bin/env python3
"""
Generate editable PPTX with one figure per slide for JATIS submission.

For flow-diagram slides (Pipeline, Gap Map), every box, arrow, and label
is a separate editable shape so the user can freely rearrange and restyle.
For data-figure slides (evaluation plots, simulation heatmaps, etc.),
the original PNG is embedded since those are generated by matplotlib.
"""

from pptx import Presentation
from pptx.util import Inches, Pt, Emu
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.enum.shapes import MSO_SHAPE
from pptx.dml.color import RGBColor
from pptx.oxml.ns import qn
from pathlib import Path

OUT_DIR = Path(__file__).resolve().parent

# Reusable colours
CLR_TEAL     = RGBColor(0x4E, 0xC5, 0xBA)   # teal-ish
CLR_SKY      = RGBColor(0x5B, 0xAF, 0xD0)   # sky blue
CLR_SAGE     = RGBColor(0xAF, 0xCF, 0xB3)   # sage green
CLR_CREAM    = RGBColor(0xF5, 0xE6, 0xBE)   # cream / yellow
CLR_LBBLUE   = RGBColor(0xD0, 0xE8, 0xF0)   # light baby blue
CLR_LTEAL    = RGBColor(0xC5, 0xE8, 0xE0)   # light teal
CLR_PINK     = RGBColor(0xF0, 0xA0, 0xA0)   # salmon/pink
CLR_CORAL    = RGBColor(0xE8, 0x80, 0x70)   # coral
CLR_DCORAL   = RGBColor(0xC8, 0x60, 0x50)   # dark coral
CLR_PURPLE   = RGBColor(0x90, 0x80, 0xB8)   # muted purple
CLR_LAVENDER = RGBColor(0xE0, 0xD8, 0xF0)   # lavender
CLR_DKGREY   = RGBColor(0x33, 0x33, 0x33)
CLR_WHITE    = RGBColor(0xFF, 0xFF, 0xFF)
CLR_BLACK    = RGBColor(0x00, 0x00, 0x00)


# ── Helpers ──────────────────────────────────────────────────────────

def _add_box(slide, left, top, width, height, fill_clr, text,
             font_size=Pt(11), bold=False, border_clr=None, border_width=Pt(1),
             text_color=CLR_DKGREY, shape_type=MSO_SHAPE.ROUNDED_RECTANGLE,
             anchor=MSO_ANCHOR.MIDDLE):
    """Add a filled rectangle with centred text.  Returns the shape."""
    shp = slide.shapes.add_shape(shape_type, left, top, width, height)
    shp.fill.solid()
    shp.fill.fore_color.rgb = fill_clr
    if border_clr:
        shp.line.fill.solid()
        shp.line.fill.fore_color.rgb = border_clr
        shp.line.width = border_width
    else:
        shp.line.fill.background()          # no border
    tf = shp.text_frame
    tf.word_wrap = True
    tf.auto_size = None
    tf.paragraphs[0].alignment = PP_ALIGN.CENTER
    tf.paragraphs[0].text = text
    tf.paragraphs[0].font.size = font_size
    tf.paragraphs[0].font.bold = bold
    tf.paragraphs[0].font.color.rgb = text_color
    # vertical centering
    txBody = shp._element.txBody
    bodyPr = txBody.find(qn('a:bodyPr'))
    bodyPr.set('anchor', 'ctr')
    return shp


def _add_arrow(slide, x1, y1, x2, y2, color=CLR_DKGREY, width=Pt(2)):
    """Add a straight connector arrow from (x1,y1) → (x2,y2)."""
    from lxml import etree
    cx = slide.shapes.add_connector(
        1,  # straight connector
        x1, y1, x2, y2)
    cx.begin_x, cx.begin_y = x1, y1
    cx.end_x, cx.end_y = x2, y2
    ln = cx.line
    ln.fill.solid()
    ln.fill.fore_color.rgb = color
    ln.width = width
    # arrowhead at end — work with the raw XML
    spPr = cx._element.find(qn('a:spPr'))
    if spPr is None:
        cxSp = cx._element
        spPr = cxSp.find('.//' + qn('a:spPr'))
    if spPr is None:
        # connector shape stores properties under cxnSp/spPr
        spPr = cx._element.makeelement(qn('a:spPr'), {})
        cx._element.append(spPr)
    ln_elem = spPr.find(qn('a:ln'))
    if ln_elem is None:
        ln_elem = etree.SubElement(spPr, qn('a:ln'))
    tail = etree.SubElement(ln_elem, qn('a:tailEnd'))
    tail.set('type', 'triangle')
    tail.set('w', 'med')
    tail.set('len', 'med')
    return cx


def _add_text(slide, left, top, width, height, text,
              font_size=Pt(10), bold=False, color=CLR_DKGREY,
              alignment=PP_ALIGN.CENTER):
    """Add a plain text box (no fill, no border)."""
    txBox = slide.shapes.add_textbox(left, top, width, height)
    tf = txBox.text_frame
    tf.word_wrap = True
    p = tf.paragraphs[0]
    p.text = text
    p.font.size = font_size
    p.font.bold = bold
    p.font.color.rgb = color
    p.alignment = alignment
    return txBox


def _add_oval(slide, left, top, width, height, fill_clr, text,
              font_size=Pt(10), bold=True, text_color=CLR_WHITE):
    """Oval / ellipse shape with centred text."""
    shp = slide.shapes.add_shape(MSO_SHAPE.OVAL, left, top, width, height)
    shp.fill.solid()
    shp.fill.fore_color.rgb = fill_clr
    shp.line.fill.background()
    tf = shp.text_frame
    tf.word_wrap = True
    tf.paragraphs[0].alignment = PP_ALIGN.CENTER
    tf.paragraphs[0].text = text
    tf.paragraphs[0].font.size = font_size
    tf.paragraphs[0].font.bold = bold
    tf.paragraphs[0].font.color.rgb = text_color
    txBody = shp._element.txBody
    bodyPr = txBody.find(qn('a:bodyPr'))
    bodyPr.set('anchor', 'ctr')
    return shp


# ── Slide builders ───────────────────────────────────────────────────

def _slide_pipeline(prs):
    """Fig. 2 — PI-DC-DVS Pipeline (fully decomposed editable shapes)."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    # Title
    _add_text(slide, Inches(0.3), Inches(0.1), Inches(12.7), Inches(0.55),
              'Fig. 2 — PI-DC-DVS Pipeline',
              font_size=Pt(24), bold=True)

    # ── Top input boxes ──
    bw, bh = Inches(2.6), Inches(0.85)
    y_top = Inches(1.0)
    x_dvs = Inches(1.2)
    x_aux = Inches(5.3)
    x_phys = Inches(9.5)

    _add_box(slide, x_dvs, y_top, bw, bh, CLR_TEAL,
             'DVS Main Channel\ne(t, x, y, p)', font_size=Pt(13), bold=True,
             text_color=CLR_WHITE, border_clr=CLR_DKGREY)

    _add_box(slide, x_aux, y_top, bw, bh, CLR_SKY,
             'Auxiliary Channels\nT(t), a(t), I(t)', font_size=Pt(13), bold=True,
             text_color=CLR_WHITE, border_clr=CLR_DKGREY)

    _add_box(slide, x_phys, y_top, bw, bh, CLR_SAGE,
             'Physics Model\n(A5 Pixel Model)', font_size=Pt(13), bold=True,
             text_color=CLR_DKGREY, border_clr=CLR_DKGREY)

    # ── Stage boxes (wider) ──
    sw, sh = Inches(8.2), Inches(0.85)
    x_stage = Inches(2.5)

    stages = [
        ('Stage 1: Noise Forward Model Construction',
         '\u03bb_noise(x,y,t) = F(\u03b8, T(t), bias, I_bg)',
         CLR_CREAM, Inches(2.15)),
        ('Stage 2: Bayesian Inverse Problem Solving (G1)',
         '\u03b8 = argmin D(e_obs, F(\u03b8)) \u2014 MLE / Variational / DeepClean-type NN (G2)',
         CLR_LBBLUE, Inches(3.25)),
        ('Stage 3: Residual Event Stream Generation',
         'e_residual = e_obs \u2296 F(\u03b8) \u2014 Probabilistic Thinning / Rate Subtraction',
         CLR_LTEAL, Inches(4.35)),
        ('Stage 4 (G4): Template-free Object Detection',
         'Residual anomaly detection \u2192 shift-and-stack \u2192 Statistical test \u2192 Cataloging',
         CLR_PINK, Inches(5.45)),
        ('Stage 5: Physical Validation',
         'PSD test / Injection-Recovery / Known Object / Blind test',
         CLR_LAVENDER, Inches(6.55)),
    ]

    for title, subtitle, clr, y_pos in stages:
        box = _add_box(slide, x_stage, y_pos, sw, sh, clr,
                       title, font_size=Pt(12), bold=True,
                       text_color=CLR_DKGREY,
                       border_clr=CLR_DKGREY, border_width=Pt(0.75))
        # subtitle as second paragraph
        tf = box.text_frame
        p2 = tf.add_paragraph()
        p2.text = subtitle
        p2.font.size = Pt(10)
        p2.font.color.rgb = CLR_DKGREY
        p2.alignment = PP_ALIGN.CENTER

    # ── Arrows: inputs → Stage 1 ──
    mid_s1_y = Inches(2.15)
    mid_s1_x = x_stage + sw // 2
    _add_arrow(slide, x_dvs + bw // 2, y_top + bh,
               x_stage + Inches(1.5), mid_s1_y)
    _add_arrow(slide, x_aux + bw // 2, y_top + bh,
               mid_s1_x, mid_s1_y)
    _add_arrow(slide, x_phys + bw // 2, y_top + bh,
               x_stage + sw - Inches(1.5), mid_s1_y)

    # Arrows between stages
    for i in range(len(stages) - 1):
        _, _, _, y1 = stages[i]
        _, _, _, y2 = stages[i + 1]
        _add_arrow(slide, mid_s1_x, y1 + sh, mid_s1_x, y2)

    # Caption
    _add_text(slide, Inches(0.3), Inches(7.15), Inches(12.7), Inches(0.3),
              'System architecture of the PI-DC-DVS noise inverse problem pipeline. '
              'All boxes and arrows are individually editable.',
              font_size=Pt(11))


def _slide_gapmap(prs):
    """Fig. 1 — Gap Map (fully decomposed editable shapes)."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    _add_text(slide, Inches(0.3), Inches(0.1), Inches(12.7), Inches(0.55),
              'Fig. 1 — DVS \u00d7 Noise Inverse Problem: Four Domains and Five Gaps (G1\u2013G5)',
              font_size=Pt(22), bold=True)

    # Domain boxes (large, rounded)
    dw, dh = Inches(2.8), Inches(2.2)
    _add_box(slide, Inches(0.6), Inches(1.0), dw, dh, CLR_TEAL,
             'A. DVS Noise\nPhysical Modeling\n(5 papers)',
             font_size=Pt(14), bold=True, text_color=CLR_DKGREY,
             border_clr=CLR_DKGREY, border_width=Pt(2))
    _add_box(slide, Inches(3.7), Inches(1.0), dw, dh, CLR_SKY,
             'B. DVS Noise\nFiltering Methods\n(7 papers)',
             font_size=Pt(14), bold=True, text_color=CLR_DKGREY,
             border_clr=CLR_DKGREY, border_width=Pt(2))
    _add_box(slide, Inches(0.6), Inches(4.6), dw, dh, CLR_SAGE,
             'C. DVS Astronomy\n& Space Apps\n(5 papers)',
             font_size=Pt(14), bold=True, text_color=CLR_DKGREY,
             border_clr=CLR_DKGREY, border_width=Pt(2))
    _add_box(slide, Inches(3.7), Inches(4.6), dw, dh, CLR_CREAM,
             'D. Noise Inverse\nProblem (non-DVS)\n(7 papers)',
             font_size=Pt(14), bold=True, text_color=CLR_DKGREY,
             border_clr=CLR_DKGREY, border_width=Pt(2))

    # Gap ovals (right side)
    gx = Inches(8.0)
    gw, gh = Inches(2.8), Inches(1.1)
    gaps = [
        ('G1\nBayesian Inverse\nFormulation', CLR_PINK, Inches(1.0)),
        ('G2\nAuxiliary Channel\nNoise Prediction', CLR_CORAL, Inches(2.3)),
        ('G3 \u2605\nAstronomy-specific\nPipeline', CLR_CORAL, Inches(3.6)),
        ('G4 \u2605\nTemplate-free\nObject Detection', CLR_DCORAL, Inches(4.9)),
        ('G5\nSciDVS + Large Tel.\nIntegrated Demo', CLR_PURPLE, Inches(6.2)),
    ]
    for text, clr, y in gaps:
        _add_oval(slide, gx, y, gw, gh, clr, text,
                  font_size=Pt(11), bold=True, text_color=CLR_WHITE)

    # Arrows: A+B → G1
    _add_arrow(slide, Inches(3.7) + dw, Inches(1.0) + dh // 2,
               gx, Inches(1.0) + gh // 2,
               color=CLR_DKGREY, width=Pt(1.5))
    # B+D → G2
    _add_arrow(slide, Inches(3.7) + dw, Inches(1.0) + dh,
               gx, Inches(2.3) + gh // 2,
               color=CLR_DKGREY, width=Pt(1.5))
    # Vertical gap chain: G1→G2→G3→G4→G5
    for i in range(len(gaps) - 1):
        _, _, y1 = gaps[i]
        _, _, y2 = gaps[i + 1]
        _add_arrow(slide, gx + gw // 2, y1 + gh,
                   gx + gw // 2, y2,
                   color=CLR_DCORAL, width=Pt(1.5))

    # Caption
    _add_text(slide, Inches(0.3), Inches(7.15), Inches(12.7), Inches(0.3),
              'Gap map: four surveyed domains (A\u2013D) and five identified gaps (G1\u2013G5). '
              'All shapes are individually editable.',
              font_size=Pt(11))


def _slide_image(prs, fig_info):
    """Standard slide: embedded PNG + title + caption."""
    slide = prs.slides.add_slide(prs.slide_layouts[6])

    # Title
    _add_text(slide, Inches(0.5), Inches(0.2), Inches(12), Inches(0.6),
              fig_info['title'], font_size=Pt(24), bold=True)

    # Image
    img_path = OUT_DIR / fig_info['file']
    if img_path.exists():
        max_w = Inches(11)
        max_h = Inches(5.5)
        pic = slide.shapes.add_picture(str(img_path),
                                       Inches(1.2), Inches(0.9),
                                       width=max_w)
        if pic.height > max_h:
            ratio = max_h / pic.height
            pic.width = int(pic.width * ratio)
            pic.height = max_h
        pic.left = int((prs.slide_width - pic.width) / 2)

    # Caption
    _add_text(slide, Inches(0.5), Inches(6.7), Inches(12), Inches(0.7),
              fig_info['caption'], font_size=Pt(14))


# ── Main ─────────────────────────────────────────────────────────────

IMAGE_FIGURES = [
    {
        'file': 'fig3_evaluation.png',
        'title': 'Fig. 3 — Systematic Evaluation',
        'caption': 'Boxplot comparison (NRR, SPR, F1, AUC) of three methods on 20 EBSSA recordings.',
    },
    {
        'file': 'fig5_per_recording.png',
        'title': 'Fig. 4 — Per-Recording Comparison',
        'caption': 'Per-recording noise removal rate for Fano filter, PI-DC-DVS NN, and temporal filter.',
    },
    {
        'file': 'fig4_a5_simulation.png',
        'title': 'Fig. 5 — A5 Model Simulation',
        'caption': 'Noise rate and SNR improvement across temperature\u2013illuminance parameter space.',
    },
    {
        'file': 'fig6_demo.png',
        'title': 'Fig. 6 — Noise Inverse Demo',
        'caption': 'Raw events \u2192 noise map \u2192 P_noise distribution \u2192 residual with satellite trail.',
    },
    {
        'file': 'fig7_snr.png',
        'title': 'Fig. 7 — S/N Improvement',
        'caption': 'Fano factor map, temporal dynamics, and per-pixel SNR distribution.',
    },
]


def build_pptx():
    prs = Presentation()
    prs.slide_width = Inches(13.333)
    prs.slide_height = Inches(7.5)

    # Slide 1: Gap map (editable shapes)
    _slide_gapmap(prs)

    # Slide 2: Pipeline (editable shapes)
    _slide_pipeline(prs)

    # Slides 3–7: data figures (embedded PNGs)
    for fig in IMAGE_FIGURES:
        _slide_image(prs, fig)

    out_path = OUT_DIR / 'figures_jatis.pptx'
    prs.save(str(out_path))
    print(f"PPTX saved: {out_path}")


if __name__ == '__main__':
    build_pptx()
